/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.cCliente;
import Modelo.mUser;
import Controlador.cUser;
import Modelo.Valida;
import Modelo.crypt;
import Modelo.mCliente;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Fran
 */
public class pnlLogin extends javax.swing.JPanel {

    /**
     * Creates new form pnlLogin
     */
    
    private mUser modeloUser;
    private cUser controladorUser;
    crypt cry = new crypt();
    
    private int idTipoUs;
    private int idUsers;
    private int idCuenta;
    

    public pnlLogin() {
        initComponents();
        
        txtUser.setDocument(new Valida(30, "[a-zA-Z0-9]*"));
        txtContra.setDocument(new Valida(8, "[a-zA-Z0-9]*"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBg = new com.k33ptoo.components.KGradientPanel();
        imgLogo = new javax.swing.JLabel();
        btnIngresar = new com.k33ptoo.components.KButton();
        pLogin = new com.k33ptoo.components.KGradientPanel();
        txtUser = new javax.swing.JTextField();
        imgContr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        btnRecuperar = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pBg.setkBorderRadius(0);
        pBg.setkEndColor(new java.awt.Color(102, 255, 51));
        pBg.setkStartColor(new java.awt.Color(0, 102, 102));
        pBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoinicio.png"))); // NOI18N
        imgLogo.setText("jLabel3");
        pBg.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 660, 170));

        btnIngresar.setText("Ingresar");
        btnIngresar.setkBorderRadius(20);
        btnIngresar.setkEndColor(new java.awt.Color(153, 153, 153));
        btnIngresar.setkHoverForeGround(new java.awt.Color(51, 153, 0));
        btnIngresar.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        btnIngresar.setkStartColor(new java.awt.Color(153, 153, 153));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        pBg.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 170, 50));

        pLogin.setkEndColor(new java.awt.Color(0, 0, 0));
        pLogin.setkStartColor(new java.awt.Color(0, 0, 0));

        imgContr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contraicon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Has olvidado tu contraseña:");

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usericon.png"))); // NOI18N
        imgUser.setMaximumSize(new java.awt.Dimension(86, 101));
        imgUser.setMinimumSize(new java.awt.Dimension(86, 101));

        btnRecuperar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRecuperar.setForeground(new java.awt.Color(0, 153, 0));
        btnRecuperar.setText("Recuperar contraseña");
        btnRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuperarMouseClicked(evt);
            }
        });

        btnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 153, 0));
        btnRegistro.setText("Cree una cuenta");
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Aun no tiene cuenta: ");

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pLoginLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRegistro))
                        .addGroup(pLoginLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnRecuperar)))
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgContr))
                        .addGap(28, 28, 28)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(txtContra))
                        .addGap(29, 29, 29)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgContr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        pBg.add(pLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 570, 360));

        add(pBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 830, 670));
    }// </editor-fold>//GEN-END:initComponents
        public void SelectID() throws SQLException {
        try {
            cUser ctUser = new cUser();
            ctUser.idtipoUser = idTipoUs;
            ctUser.idUser = idUsers;
            ResultSet rs = ctUser.SelecionarNivel();

            if (rs.next()) {
                if (idTipoUs == 1) {
                    idCuenta = rs.getInt("idUsuario");
                    vDashboard dashboardAdmin = new vDashboard();
                    dashboardAdmin.setVisible(true);
                }
                if (idTipoUs == 2) {
                    idCuenta = rs.getInt("idUsuario");
                    vDashboardMec dashboardMecanico = new vDashboardMec();
                    dashboardMecanico.setVisible(true);
                }
                if (idTipoUs == 3) {
                    idCuenta = rs.getInt("idUsuario");
                    vDashboardCont dashboardContador = new vDashboardCont();
                    dashboardContador.setVisible(true);
                }
                if (idTipoUs == 4) {
                    idCuenta = rs.getInt("idUsuario");
                    vDashboardRece dashboardRecep = new vDashboardRece();
                    dashboardRecep.setVisible(true);
                }
                
                rs.close();

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    
    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
                try {
            try {
                cUser ct = new cUser();
                ct.usuario = txtUser.getText();
                ct.contra = txtContra.getText();
                ct.contra = cry.encryptPassword(txtContra.getText());
                ResultSet rs=ct.Login();
                if (rs.next()) {
                    idTipoUs = rs.getInt("idTipo");
                    idUsers = rs.getInt("idUsuario");
                    rs.close();
                    SelectID();
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
                }

            } catch (SQLException ex) {
                System.out.println(ex.toString() + " ERROR");
            }

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        vRegistro registro = new vRegistro();
        registro.setVisible(true);
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void btnRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarMouseClicked
        vRecupContra recup = new vRecupContra();
        recup.setVisible(true);
    }//GEN-LAST:event_btnRecuperarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.k33ptoo.components.KButton btnIngresar;
    private javax.swing.JLabel btnRecuperar;
    private javax.swing.JLabel btnRegistro;
    private javax.swing.JLabel imgContr;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.k33ptoo.components.KGradientPanel pBg;
    private com.k33ptoo.components.KGradientPanel pLogin;
    private javax.swing.JPasswordField txtContra;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
