/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.cCliente;
import Controlador.cRegistro;
import Controlador.cUsuario;
import Modelo.NivelesUsuario;
import Modelo.mCliente;
import Modelo.mRegistro;
import Modelo.mUsuario;

/**
 *
 * @author Fran
 */
public class pnlRegistroGen extends javax.swing.JPanel {

    private mCliente modeloCliente;
    private cCliente controladorCliente;
    private mRegistro modeloUsuario;
    private cRegistro controladorUsuario;
    private NivelesUsuario modeNivelesUsuario;
    /**
     * Creates new form pnlRegistroGen
     */
    public pnlRegistroGen() {
        initComponents();
        modeloUsuario = new mRegistro();
        modeNivelesUsuario = new NivelesUsuario();
        controladorUsuario = new cRegistro(this, modeloUsuario,modeNivelesUsuario);
        modeNivelesUsuario.llenarComboBox(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLogin = new com.k33ptoo.components.KGradientPanel();
        txtCorre = new javax.swing.JTextField();
        txtUs = new javax.swing.JTextField();
        txtContras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUser = new com.k33ptoo.components.KButton();
        cbLista = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pLogin.setkEndColor(new java.awt.Color(0, 102, 102));
        pLogin.setkStartColor(new java.awt.Color(102, 255, 102));
        pLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pLogin.add(txtCorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 602, 39));
        pLogin.add(txtUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 602, 39));
        pLogin.add(txtContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 602, 39));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Correo electronico:");
        pLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Registro");
        pLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña:");
        pLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        btnUser.setText("Registrar Usuario");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        pLogin.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        cbLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pLogin.add(cbLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 190, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Usuario:");
        pLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        add(pLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.k33ptoo.components.KButton btnUser;
    public javax.swing.JComboBox<String> cbLista;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public com.k33ptoo.components.KGradientPanel pLogin;
    public javax.swing.JTextField txtContras;
    public javax.swing.JTextField txtCorre;
    public javax.swing.JTextField txtUs;
    // End of variables declaration//GEN-END:variables
}
